version: '2.0'
services:
  app:
    # image: divante/vue-storefront-api:latest
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    env_file: docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    volumes:
      - './config:/var/www/config'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '8080:8080'
  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
  kibana:
    extends:
      file: docker-compose.yml
      service: kibana
  redis:
    extends:
      file: docker-compose.yml
      service: redis
volumes:
  esdat1:
