version: '2'
services:
  es1:
    build: elasticsearch/
    container_name: es1
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdat1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - es1

  redis:  
    image: redis

    ports:
      - "6379:6379"


volumes:
  esdat1:
    driver: local

networks:
  esnet:
