version: '2.0'
services:
  elasticsearch:
    image: divante/vue-storefront-elasticsearch:5.6.9
    # build: docker/elasticsearch/
    env_file: docker/elasticsearch/default.env
    volumes:
      - 'esdat1:/usr/share/elasticsearch/data'
    expose:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: divante/vue-storefront-kibana:5.6.9
    # build: docker/kibana/
    depends_on:
      - elasticsearch
    env_file: docker/kibana/default.env
    ports:
      - '5601:5601'
  redis:
    image: 'redis:4-alpine'
    expose:
      - 6379
volumes:
  esdat1:
