apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront-api
spec:
  selector:
    matchLabels:
      app: vue-storefront-api
  replicas: 1
  template:
    metadata:
      labels:
        app: vue-storefront-api
    spec:
      containers:
      - name: vue-storefront-api
        image: divante/vue-storefront-api:latest
        env:
        - name: BIND_HOST
          value: 0.0.0.0
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: VS_ENV
          value: dev
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/www/config
          name: code
          subPath: config
        - mountPath: /var/www/migrations
          name: code
          subPath: migrations
          readOnly: true
        - mountPath: /var/www/package.json
          name: code
          subPath: package.json
          readOnly: true
        - mountPath: /var/www/scripts
          name: code
          subPath: scripts
          readOnly: true
        - mountPath: /var/www/src
          name: code
          subPath: src
          readOnly: true
        - mountPath: /var/www/var
          name: code
          subPath: var
          readOnly: true
        - mountPath: /var/www/dist
          name: tmpfs
      restartPolicy: Always
      volumes:
      - name: code
        hostPath:
          path: "/root/vue-storefront-api"
      - name: tmpfs
        emptyDir:
          medium: Memory
